### PR TITLE
Feature to add plugins for custom item processing and middleware for manipulating HTTP requests before downloading files

### PR DESCRIPTION
**Pull request by jprichards**
This is a straight-up port of Middleware from Munki - https://github.com/munki/munki/blob/v3.3.1/code/client/munkilib/fetch.py#L73

Future enhancements would be to add the actual middleware-like functionality for the gurl download. Resulting in a plugin + middleware combo if desired.

But the main use case for me: some items in Bootstrap.json I will define with type:plugin, with a name (for DEPNotify), and AirWatch app ID. Then the VMware AirWatch plugin (in development) will make the necessary API calls to push the app via the various AirWatch Agent software distribution mechanisms. Future enhancements - the plugin will have the ability to take in a Profile ID, to orchestrate the order of profile installs if needed - for example, downloading a VPN software before pushing a script/profile to bind the machine.

### CODE REVIEW

**Comment by kcrawford** [comment]
@jprichards That could be very useful for me right now.  I am looking to get specific apps/pkgs installed at bootstrap time that are hosted within AirWatch.  Where can I find the referenced plugin?

**Comment by jprichards** [comment]
@kcrawford I will have an alpha version up soon and will send it to you

**Comment by LcTrKiD** [comment]
I’m interested in the plugin too

**Comment by erikng** [comment]
@jprichards this is going to need to be rewritten for python3 and I haven't heard from you in basically a year on this diff. Closing.

**Pull request closed without merging**
